dt: 0.1
integrator_type: rk4
input_limit: 50.0
hydrodynamics:
  mass: 29.0
  Iz: 10.0
  B: 0.79
  Xu_dot: -5.0
  Yv_dot: -5.0
  Nr_dot: -1.0
  Xu: 20.0
  Yv: 20.0
  Nr: 20.0
topics:
  odom: /heron/odom
  left_thruster_cmd: /heron/left_thruster_cmd
  right_thruster_cmd: /heron/right_thruster_cmd
